### ISSUE TITLE
[FEAT] Setup Layout for `Home` Page

### ISSUE THREAD

**Issue by xynree** [the-collab-lab/tcl-46-smart-shopping-list#80]
Setup layout to match mockup:

![image](https://user-images.githubusercontent.com/77255525/186551087-b9eafaaf-45ca-48e2-b3c8-def151cb68c2.png)
![image](https://user-images.githubusercontent.com/77255525/186551277-2b3735a4-142f-45b2-8275-a18856b6b169.png)

Considerations:
- [x] `Home` should be changed to `Manage Lists` once a token is generated
- [x] Mobile has single column while desktop has double column layout

**Comment by h-yung** [comment]
Closed with PR #93
